version: "3"

services:
  fakel:
    build:
      context: fakel
      dockerfile: Dockerfile
    image: jojopko/fakel:latest
    command: python -m fakel
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      DEBUG_MODE: 'false'